context: {}
package:

  name: ecrad_gui
  version: 1.0.18

source:
  git_rev: 1.0.18
  git_url: https://github.com/AreWeDreaming/ECRad_GUI

build:
  number: 1
  entry_points:
    - ecrad_gui = ecrad_gui.ECRad_GUI_Application:main

requirements:
  build:
    - python
    - numpy >=1.21
    - pip >=21.0
    - setuptools >=57.4
    - build >=0.7
  run:
    - python
    - numpy >=1.21
    - scipy >=1.7.3
    - matplotlib
    - hdf5
    - netcdf4 >=1.5.6
    - h5py
    - wxpython
    - f90nml >=1.3.1
    - plasma_math_tools
    - ecrad_core
    - ecrad_pylib

